-   id: keywordscan
    name: KeywordScan
    description: "Scan keywords in text files so that they don't get added to the GitHub."
    entry: keywordscan
    language: python
    types: ["text"]
    args: []
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 3.4.0
